import "./globals.css";
import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import { ToastContainer} from 'react-toastify';
import Navbar from '../components/sharedLayout/Navbar';
import Footer from '../components/sharedLayout/Footer';
import { Suspense } from "react";
import GlobalLoading from "./loading";

const hindSiliguri = Hind_Siliguri({
  
  weight: ["400", "500", "600", "700"],
  subsets: ["latin" , "bengali"],
});



export const metadata: Metadata = {
  title: "BazarDor Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.className} h-full antialiased`}
    >
   
    <body className="min-h-full flex flex-col">
      
      <Suspense fallback={<GlobalLoading></GlobalLoading>}>
        <main >
            <Navbar />

            {children}

            <Footer />
        </main>
      </Suspense>
   

      <ToastContainer />
    </body>
   
    </html>
  );
}
