import "./globals.css";
import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import { ToastContainer} from 'react-toastify';
import Navbar from '../components/sharedLayout/Navbar';
import Footer from '../components/sharedLayout/Footer';

const hindSiliguri = Hind_Siliguri({
  variable: "--font-hind-siliguri",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin" , "bengali"],
});



export const metadata: Metadata = {
  title: "BazarDor Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.variable}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Navbar />

          {children}

          <Footer />
          
      <ToastContainer />
      </body>
    </html>
  );
}
